include: package:flutter_driver_app/lib/**/*.dart

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false
    prefer_single_quotes: true
